site_name: Home

theme:
  name: null
  custom_dir: 'cinder'

nav:
    - Sobre o produto:
      - Visão de produto: visao_produto.md
      - Objetivos de produto: objetivos_produto.md
      - Objetivos de negócio: objetivos_negocios.md
      - Metodologia: metodologia.md
      - Legislação e normas: pre-rastreabilidade/legislacao.md
      - Gerenciamento de riscos e plano de contingência: pre-rastreabilidade/riscos.md
      - Estimativa de custos: pre-rastreabilidade/estimativa_custos.md

    - Arquit. do Software: arquitetura.md

    - Arquit. da informação:
      - Heurísticas de Nielsen: prototipos/heuristicas.md
      - Protótipo de baixa fidelidade: prototipos/prototipo_baixa.md
      - Protótipo de alta fidelidade: prototipos/prototipo_alta.md

    - Requisitos:
      - Rich Pictures: pre-rastreabilidade/rich_picture.md
      - Requisitos funcionais e não funcionais: elicitacao_requisitos/requisitos.md
      - MoScoW: elicitacao_requisitos/moscow.md
      - First Things First: elicitacao_requisitos/first_things.md
      - NFR: elicitacao_requisitos/nfr.md
      - Especificação suplementar: elicitacao_requisitos/especificacao_suplementar.md
      - Histórias de usuário: pos-rastreabilidade/user_story.md
      - Épicos: pos-rastreabilidade/epicos.md
      - Backlog: pos-rastreabilidade/backlog.md

    - Modelagem:
      - Casos de uso: pos-rastreabilidade/casos_uso.md
      - Diagrama de casos de uso: pos-rastreabilidade/diagramas_casos_uso.md
      - Diagrama de arquitetura: modelagem/diagrama_arquitetura.md
      - Diagrama de atividades: modelagem/diagrama_atividades.md
      - Diagrama de classes: modelagem/diagrama_classes.md
      - Diagrama de componentes: modelagem/diagrama_componentes.md
      - Diagrama de pacotes: modelagem/diagrama_pacotes.md

    - Manuais:
      - Manual de usuário: manual_usuario.md
      - Manual de uso: manual_uso.md
      - Manual de instalação: manual_instalacao.md

    - Testes: testes.md



